# Generated by Django 6.0.6 on 2026-06-25 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditalProvisorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome_edital",
                    models.CharField(
                        default="", max_length=255, verbose_name="Nome do Edital"
                    ),
                ),
                (
                    "area_estudo",
                    models.CharField(
                        default="", max_length=255, verbose_name="Área de Estudo"
                    ),
                ),
                (
                    "detalhes_edital",
                    models.TextField(
                        blank=True, default="", verbose_name="Detalhes do Edital"
                    ),
                ),
                (
                    "nome_instituto",
                    models.CharField(
                        choices=[
                            ("isi_biomassa", "ISI Biomassa"),
                            ("ist_alimentos", "IST Alimentos e Bebidas"),
                            ("ist_construcao", "Faculdade da Construção"),
                            ("fatec_cg", "FATEC - Campo Grande"),
                            ("departamento_regional", "DR"),
                        ],
                        help_text="Selecione o Instituto",
                        max_length=255,
                        verbose_name="Nome do Instituto",
                    ),
                ),
                (
                    "email_solicitante",
                    models.EmailField(
                        help_text="Insira o seu e-mail",
                        max_length=254,
                        verbose_name="E-mail do Solicitante",
                    ),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("endereco", models.TextField(verbose_name="Endereço")),
                (
                    "documento_anexo",
                    models.FileField(
                        blank=True,
                        upload_to="editais/",
                        verbose_name="Termo de Parceria e/ou Plano de Projeto (PDF)",
                    ),
                ),
                (
                    "numero_vagas",
                    models.PositiveIntegerField(verbose_name="Número de Vagas"),
                ),
                (
                    "modalidade_bolsa",
                    models.CharField(
                        choices=[
                            ("nivel_1", "Nível 1"),
                            ("nivel_2", "Nível 2"),
                            ("nivel_3", "Nível 3"),
                            ("nivel_4", "Nível 4"),
                        ],
                        max_length=50,
                        verbose_name="Modalidade da Bolsa",
                    ),
                ),
                (
                    "valor_total_bolsa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Total da Bolsa (R$)",
                    ),
                ),
                (
                    "valor_bolsa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor da Bolsa (R$)",
                    ),
                ),
                (
                    "valor_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Mínimo (R$)",
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Máximo (R$)",
                    ),
                ),
                (
                    "modalidade_atuacao",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("remota", "Remota")],
                        default="presencial",
                        max_length=50,
                        verbose_name="Modalidade de Atuação",
                    ),
                ),
                (
                    "plataforma_tecnologica",
                    models.CharField(
                        max_length=255, verbose_name="Plataforma Tecnológica"
                    ),
                ),
                (
                    "vigencia",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="Mínimo: 15 dias. Máximo: 36 meses (1095 dias).",
                        verbose_name="Vigência (dias)",
                    ),
                ),
                (
                    "endereco_atuacao",
                    models.TextField(
                        blank=True, default="", verbose_name="Endereço de Atuação"
                    ),
                ),
                (
                    "qualificacao_minima",
                    models.CharField(
                        max_length=255, verbose_name="Qualificação Mínima"
                    ),
                ),
                (
                    "detalhes_qualificacao_minima",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Qualificação Mínima em:",
                    ),
                ),
                (
                    "conhecimento_desejavel",
                    models.TextField(
                        blank=True, default="", verbose_name="Conhecimento Desejável"
                    ),
                ),
                (
                    "conteudo_prova_teorica",
                    models.TextField(verbose_name="Conteúdo da Prova Teórica"),
                ),
                ("entrevista", models.TextField(verbose_name="Entrevista")),
                (
                    "criterios_desempate",
                    models.TextField(verbose_name="Critérios de Desempate"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("encerrado", "Encerrado"),
                            ("em_analise", "Em Análise"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="em_analise",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editais_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Edital",
                "verbose_name_plural": "Editais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DistribuicaoBolsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "experiencia",
                    models.CharField(max_length=255, verbose_name="Experiência"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade de Bolsistas"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor Unitário (R$)",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribuicoes",
                        to="editais.editalprovisorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuição de Bolsa",
                "verbose_name_plural": "Distribuições de Bolsa",
            },
        ),
        migrations.CreateModel(
            name="CronogramaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            (
                                "inicio_submissao",
                                "Início da submissão das candidaturas",
                            ),
                            (
                                "limite_submissao",
                                "Data limite para submissão das candidaturas",
                            ),
                            (
                                "resultado_aptas",
                                "Resultado das candidaturas aptas (análise documental/curricular)",
                            ),
                            ("prova_teorica", "Prova teórica"),
                            ("resultado_prova", "Resultado da prova teórica"),
                            (
                                "envio_documentacao",
                                "Envio da Documentação Comprobatória",
                            ),
                            ("entrevista", "Entrevista"),
                            ("resultado_final", "Divulgação do Resultado Final"),
                            ("outorga", "Outorga das bolsas"),
                        ],
                        max_length=50,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "data_referencia",
                    models.CharField(max_length=255, verbose_name="Data de Referência"),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, default="", verbose_name="Observação"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronograma",
                        to="editais.editalprovisorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento do Cronograma",
                "verbose_name_plural": "Eventos do Cronograma",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="AplicacaoEdital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em Análise"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Nota do avaliador",
                    ),
                ),
                (
                    "data_aplicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de aplicação"
                    ),
                ),
                (
                    "bolsista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="cadastro.cadastrobolsista",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacoes",
                        to="editais.editalprovisorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicação em Edital",
                "verbose_name_plural": "Aplicações em Editais",
                "unique_together": {("bolsista", "edital")},
            },
        ),
    ]
