# Generated by Django 6.0.7 on 2026-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0004_remove_cronogramaevento_data_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editalprovisorio',
            name='entrevista',
        ),
        migrations.AddField(
            model_name='editalprovisorio',
            name='experiencia',
            field=models.CharField(blank=True, choices=[('Sem Experiência', 'Sem Experiência'), ('1 Ano de Experiência', '1 Ano de Experiência'), ('2 Anos ou mais', '2 Anos ou mais')], default='', max_length=50, verbose_name='Experiência'),
        ),
        migrations.AddField(
            model_name='editalprovisorio',
            name='modalidade_entrevista',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=20, verbose_name='Modalidade da Entrevista'),
        ),
        migrations.AlterField(
            model_name='cronogramaevento',
            name='data_evento',
            field=models.DateField(verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='cronogramaevento',
            name='evento',
            field=models.CharField(choices=[('inicio_submissao', 'Início da submissão das candidaturas'), ('limite_submissao', 'Data limite para submissão das candidaturas'), ('resultado_aptas', 'Resultado das candidaturas aptas (análise documental/curricular)'), ('prova_teorica', 'Prova teórica'), ('entrevista', 'Entrevista'), ('resultado_final', 'Divulgação do Resultado Final'), ('outorga', 'Outorga das bolsas')], max_length=50, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='editalprovisorio',
            name='conteudo_prova_teorica',
            field=models.TextField(blank=True, default='', verbose_name='Conteúdo da Prova Teórica'),
        ),
        migrations.AlterField(
            model_name='editalprovisorio',
            name='criterios_desempate',
            field=models.TextField(blank=True, default='', verbose_name='Critérios de Desempate'),
        ),
    ]
