# Generated by Django 6.0.7 on 2026-07-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0005_remove_editalprovisorio_entrevista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editalprovisorio',
            name='comentarios',
            field=models.TextField(blank=True, default='', verbose_name='Comentários'),
        ),
    ]
