# Generated by Django 4.2.13 on 2026-07-17 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("editais", "0006_editalprovisorio_comentarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="editalprovisorio",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editais_responsavel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="nome_instituto",
            field=models.CharField(
                choices=[
                    ("isi_biomassa", "ISI Biomassa - Três Lagoas"),
                    ("ist_alimentos", "IST Alimentos e Bebidas - Dourados"),
                    ("ist_eficiencia", "IST Eficiência Operacional - Campo Grande"),
                    ("ist_construcao", "Faculdade da Construção - Campo Grande"),
                ],
                help_text="Selecione o Instituto",
                max_length=255,
                verbose_name="Nome do Instituto",
            ),
        ),
        migrations.AlterField(
            model_name="editalprovisorio",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_analise", "Em Análise"),
                    ("aberto", "Aberto"),
                    ("encerrado", "Encerrado"),
                    ("cancelado", "Cancelado"),
                ],
                default="em_analise",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
