# Generated by Django 4.2.13 on 2026-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0012_editalprovisorio_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editalprovisorio",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_analise", "Em Análise"),
                    ("aberto", "Aberto"),
                    ("encerrado", "Fechado"),
                    ("cancelado", "Cancelado"),
                    ("excluido", "Excluído"),
                ],
                default="em_analise",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
