# Generated by Django 6.0.6 on 2026-06-25 21:10

from django.db import migrations


def criar_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for nome in ['Manager', 'ViewUser', 'ExecuteUser']:
        Group.objects.get_or_create(name=nome)


def remover_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Manager', 'ViewUser', 'ExecuteUser']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(criar_grupos, remover_grupos),
    ]
