# Generated by Django 6.0.6 on 2026-06-25 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                ("lido", models.BooleanField(default=False, verbose_name="Lido")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cadastro", "Cadastro"),
                            ("solicitacao", "Solicitação"),
                            ("sistema", "Sistema"),
                        ],
                        default="sistema",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
            },
        ),
    ]
