# Generated by Django 6.0.7 on 2026-07-17 20:23

import cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cadastro_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrobolsista',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='curriculos/', validators=[cadastro.models.validar_pdf], verbose_name='Currículo'),
        ),
    ]
