# Generated by Django 6.0.6 on 2026-06-16 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_perfil_data_nascimento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditalProvisorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome_instituto",
                    models.CharField(max_length=255, verbose_name="Nome do Instituto"),
                ),
                (
                    "email_solicitante",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail do Solicitante"
                    ),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("endereco", models.TextField(verbose_name="Endereço")),
                (
                    "numero_vagas",
                    models.PositiveIntegerField(verbose_name="Número de Vagas"),
                ),
                (
                    "modalidade_bolsa",
                    models.CharField(
                        choices=[
                            ("bolsa_mestrado", "Bolsa de Mestrado"),
                            ("bolsa_doutorado", "Bolsa de Doutorado"),
                            ("bolsa_pos_doutorado", "Bolsa de Pós-Doutorado"),
                            ("bolsa_ic", "Bolsa de Iniciação Científica"),
                            ("bolsa_extensao", "Bolsa de Extensão"),
                            (
                                "bolsa_desenvolvimento",
                                "Bolsa de Desenvolvimento Tecnológico",
                            ),
                            ("bolsa_aperfeicoamento", "Bolsa de Aperfeiçoamento"),
                        ],
                        max_length=50,
                        verbose_name="Modalidade da Bolsa",
                    ),
                ),
                (
                    "plataforma_tecnologica",
                    models.CharField(
                        max_length=255, verbose_name="Plataforma Tecnológica"
                    ),
                ),
                ("vigencia", models.CharField(max_length=255, verbose_name="Vigência")),
                (
                    "endereco_atuacao",
                    models.TextField(verbose_name="Endereço de Atuação"),
                ),
                (
                    "qualificacao_minima",
                    models.TextField(verbose_name="Qualificação Mínima"),
                ),
                (
                    "experiencia_minima",
                    models.TextField(
                        verbose_name="Experiência Mínima (Profissional/Acadêmica)"
                    ),
                ),
                (
                    "conhecimento_desejavel",
                    models.TextField(
                        blank=True, default="", verbose_name="Conhecimento Desejável"
                    ),
                ),
                (
                    "conteudo_prova_teorica",
                    models.TextField(verbose_name="Conteúdo da Prova Teórica"),
                ),
                ("entrevista", models.TextField(verbose_name="Entrevista")),
                (
                    "criterios_desempate",
                    models.TextField(verbose_name="Critérios de Desempate"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("publicado", "Publicado"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editais_provisorios_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editais_provisorios",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edital Provisório",
                "verbose_name_plural": "Editais Provisórios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CronogramaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            (
                                "inicio_submissao",
                                "Início da submissão das candidaturas",
                            ),
                            (
                                "limite_submissao",
                                "Data limite para submissão das candidaturas",
                            ),
                            (
                                "resultado_aptas",
                                "Resultado das candidaturas aptas (análise documental/curricular)",
                            ),
                            ("prova_teorica", "Prova teórica"),
                            ("resultado_prova", "Resultado da prova teórica"),
                            (
                                "envio_documentacao",
                                "Envio da Documentação Comprobatória",
                            ),
                            ("entrevista", "Entrevista"),
                            ("resultado_final", "Divulgação do Resultado Final"),
                            ("outorga", "Outorga das bolsas"),
                        ],
                        max_length=50,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "data_referencia",
                    models.CharField(max_length=255, verbose_name="Data de Referência"),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, default="", verbose_name="Observação"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronogramas_provisorios",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronograma",
                        to="edital_provisorio.editalprovisorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento do Cronograma",
                "verbose_name_plural": "Eventos do Cronograma",
                "ordering": ["ordem"],
            },
        ),
    ]
