# Generated by Django 4.2.13 on 2026-07-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0008_migrate_rascunho_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="aplicacaoedital",
            name="nota_entrevista",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Nota da Entrevista",
            ),
        ),
        migrations.AlterField(
            model_name="aplicacaoedital",
            name="nota",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Nota da Prova",
            ),
        ),
    ]
