# Generated by Django 4.2.13 on 2026-07-20 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("editais", "0009_aplicacaoedital_nota_entrevista_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AplicacaoEditalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nota_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Nota da Prova Anterior",
                    ),
                ),
                (
                    "nota_nova",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Nota da Prova Nova",
                    ),
                ),
                (
                    "nota_entrevista_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Nota da Entrevista Anterior",
                    ),
                ),
                (
                    "nota_entrevista_nova",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Nota da Entrevista Nova",
                    ),
                ),
                (
                    "data_entrevista_anterior",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data da Entrevista Anterior",
                    ),
                ),
                (
                    "data_entrevista_nova",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Entrevista Nova"
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Status Anterior",
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Status Novo",
                    ),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_avaliacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="editais.aplicacaoedital",
                        verbose_name="Aplicação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Avaliação",
                "verbose_name_plural": "Logs de Avaliação",
                "ordering": ["-created_at"],
            },
        ),
    ]
