# Generated by Django 4.2.13 on 2026-08-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0010_aplicacaoeditallog"),
    ]

    operations = [
        migrations.AddField(
            model_name="aplicacaoedital",
            name="documento_resultado",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="avaliacoes/",
                verbose_name="Documento do Resultado",
            ),
        ),
    ]
