# Generated by Django 6.0.7 on 2026-07-15 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0003_data_entrevista_aplicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronogramaevento',
            name='data_referencia',
        ),
        migrations.AlterField(
            model_name='cronogramaevento',
            name='data_evento',
            field=models.DateField(default=datetime.date.today, verbose_name='Data do Evento'),
        ),
        migrations.DeleteModel(
            name='DistribuicaoBolsa',
        ),
    ]
