# Generated by Django 4.2.13 on 2026-07-17 18:00

from django.db import migrations


def forward_func(apps, schema_editor):
    EditalProvisorio = apps.get_model('editais', 'EditalProvisorio')
    EditalProvisorio.objects.filter(status='rascunho').update(status='em_analise')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0007_add_responsavel_field"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
