# Generated by Django 4.2.13 on 2026-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0011_aplicacaoedital_documento_resultado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="editalprovisorio",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Excluído em"
            ),
        ),
    ]
