# Generated by Django 6.0.6 on 2026-06-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CriterioClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "tipo_criterio",
                    models.CharField(
                        choices=[
                            ("graduacao", "Graduação"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                            (
                                "projetos_pesquisa",
                                "Participação em Projetos de Pesquisa/Atuação Profissional",
                            ),
                            (
                                "congressos",
                                "Participação em Congressos, Feiras, Eventos e Palestras",
                            ),
                            ("resumo_anais", "Resumo Publicado em Anais de Eventos"),
                            (
                                "artigo_completo_anais",
                                "Artigo Completo Publicado em Anais de Eventos",
                            ),
                            (
                                "artigo_nacional",
                                "Artigo Científico ou Capítulo de Livro Nacional Publicado",
                            ),
                            (
                                "artigo_internacional",
                                "Artigo Científico ou Capítulo de Livro Internacional Publicado",
                            ),
                            (
                                "livro_patente",
                                "Livro Publicado na Área de Interesse ou Patente Registrada",
                            ),
                            (
                                "minicurso",
                                "Participação em Minicurso (até 4 horas) na Área de Interesse",
                            ),
                            (
                                "treinamento",
                                "Treinamento (acima de 4 horas) na Área de Interesse",
                            ),
                        ],
                        default="congressos",
                        max_length=30,
                        verbose_name="Tipo de critério",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Peso"
                    ),
                ),
                (
                    "peso_maximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Usado para critérios com teto de pontuação (ex: Projetos/Pesquisa).",
                        max_digits=10,
                        verbose_name="Peso máximo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Critério de Classificação",
                "verbose_name_plural": "Critérios de Classificação",
            },
        ),
    ]
