# Generated by Django 4.2.13 on 2026-06-15 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("editais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "pontuacao_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Pontuação total"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "aplicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacoes",
                        to="editais.aplicacaoedital",
                    ),
                ),
                (
                    "classificador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacoes_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacoes",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação",
                "verbose_name_plural": "Classificações",
            },
        ),
        migrations.CreateModel(
            name="CriterioClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "tipo_criterio",
                    models.CharField(
                        choices=[
                            ("graduacao", "Graduação"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                            (
                                "projetos_pesquisa",
                                "Participação em Projetos de Pesquisa/Atuação Profissional",
                            ),
                            (
                                "congressos",
                                "Participação em Congressos, Feiras, Eventos e Palestras",
                            ),
                            ("resumo_anais", "Resumo Publicado em Anais de Eventos"),
                            (
                                "artigo_completo_anais",
                                "Artigo Completo Publicado em Anais de Eventos",
                            ),
                            (
                                "artigo_nacional",
                                "Artigo Científico ou Capítulo de Livro Nacional Publicado",
                            ),
                            (
                                "artigo_internacional",
                                "Artigo Científico ou Capítulo de Livro Internacional Publicado",
                            ),
                            (
                                "livro_patente",
                                "Livro Publicado na Área de Interesse ou Patente Registrada",
                            ),
                            (
                                "minicurso",
                                "Participação em Minicurso (até 4 horas) na Área de Interesse",
                            ),
                            (
                                "treinamento",
                                "Treinamento (acima de 4 horas) na Área de Interesse",
                            ),
                        ],
                        default="congressos",
                        max_length=30,
                        verbose_name="Tipo de critério",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Peso"
                    ),
                ),
                (
                    "peso_maximo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Usado para critérios com teto de pontuação (ex: Projetos/Pesquisa).",
                        max_digits=10,
                        verbose_name="Peso máximo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critério de Classificação",
                "verbose_name_plural": "Critérios de Classificação",
            },
        ),
        migrations.CreateModel(
            name="ClassificacaoCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Nota"
                    ),
                ),
                (
                    "classificacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="classificacao.classificacao",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="classificacao.criterioclassificacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota por Critério",
                "verbose_name_plural": "Notas por Critério",
            },
        ),
    ]
